openapi: 3.0.3
info:
  title: GPT Property Manager
  description: API to manage properties and embeddings via Supabase and Pinecone.
  version: 1.0.0

servers:
  - url: https://gpt-memory-api.onrender.com

paths:
  /supabase/property:
    post:
      operationId: addProperty
      summary: Add a new property
      description: Adds a new property to Supabase.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Property'
      responses:
        '200':
          description: Property successfully created.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Property'

  /properties:
    get:
      operationId: getAllProperties
      summary: Get all properties
      description: Retrieves a list of all properties.
      responses:
        '200':
          description: A list of properties.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Property'

    post:
      operationId: createProperty
      summary: Create a property
      description: Creates a new property and stores it.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Property'
      responses:
        '200':
          description: Property created.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Property'

  /vector-search:
    post:
      operationId: searchSimilarProperties
      summary: Search properties by text
      description: Performs a semantic search for similar properties using Pinecone.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                query:
                  type: string
                  description: The text to search for.
      responses:
        '200':
          description: Vector search result.
          content:
            application/json:
              schema:
                type: object
                properties:
                  results:
                    type: array
                    items:
                      type: string

  /github/{owner}/{repo}:
    get:
      operationId: getGithubRepoInfo
      summary: Get GitHub repo info
      description: Retrieves basic information about a GitHub repository.
      parameters:
        - name: owner
          in: path
          required: true
          description: GitHub username or organization
          schema:
            type: string
        - name: repo
          in: path
          required: true
          description: Repository name
          schema:
            type: string
      responses:
        '200':
          description: GitHub repository info.
          content:
            application/json:
              schema:
                type: object
                properties:
                  name:
                    type: string
                  stars:
                    type: integer

components:
  schemas:
    Property:
      type: object
      required:
        - title
        - description
        - price
      properties:
        title:
          type: string
          description: The title of the property
        description:
          type: string
          description: The description of the property
        price:
          type: number
          description: The price of the property