openapi: 3.0.0
info:
  title: Minimal Test
  version: 1.0.0

servers:
  - url: https://gpt-memory-api.onrender.com

paths:
  /ping:
    get:
      summary: Health check
      responses:
        '200':
          description: OK