openapi: 3.1.0
info:
  title: GPT Property Manager
  description: API to manage properties and embeddings via Supabase and Pinecone.
  version: 1.0.0

servers:
  - url: https://gpt-memory-api.onrender.com

paths:
  /supabase/property:
    post:
      operationId: addProperty
      summary: Add a new property
      description: Adds a new property to Supabase.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Property'
      responses:
        '200':
          description: Property successfully created.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Property'

  /properties:
    get:
      operationId: getAllProperties
      summary: Get all properties
      description: Retrieves all properties.
      responses:
        '200':
          description: A list of properties.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Property'

    post:
      operationId: createProperty
      summary: Create a property
      description: Creates and stores a new property.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Property'
      responses:
        '200':
          description: Property created.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Property'

  /vector-search:
    post:
      operationId: searchSimilarProperties
      summary: Semantic search for properties
      description: Searches Pinecone for similar properties by text.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - query
              properties:
                query:
                  type: string
                  description: The text to search
      responses:
        '200':
          description: Search results
          content:
            application/json:
              schema:
                type: object
                properties:
                  results:
                    type: array
                    items:
                      type: string

  /github/{owner}/{repo}:
    get:
      operationId: getGithubRepoInfo
      summary: Get GitHub repo info
      description: Retrieves basic repository data.
      parameters:
        - name: owner
          in: path
          required: true
          description: GitHub username/org
          schema:
            type: string
        - name: repo
          in: path
          required: true
          description: Repository name
          schema:
            type: string
      responses:
        '200':
          description: GitHub repository info
          content:
            application/json:
              schema:
                type: object
                properties:
                  name:
                    type: string
                  stars:
                    type: integer

components:
  schemas:
    Property:
      type: object
      description: A real estate property object.
      required:
        - title
        - description
        - price
      properties:
        title:
          type: string
          description: Property title
        description:
          type: string
          description: Property description
        price:
          type: number
          description: Property price
