openapi: 3.1.0
info:
  title: GPT Property Manager
  version: 1.0.0

servers:
  - url: https://gpt-memory-api.onrender.com

paths:
  /supabase/property:
    post:
      operationId: addProperty
      summary: Add a new property to Supabase
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Property'
      responses:
        '200':
          description: Property created
          content:
            application/json:
              schema:
                type: object

  /properties:
    get:
      operationId: getAllProperties
      summary: Get all properties
      responses:
        '200':
          description: A list of properties
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Property'
    post:
      operationId: createProperty
      summary: Create a new property
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Property'
      responses:
        '200':
          description: Property created
          content:
            application/json:
              schema:
                type: object

  /vector-search:
    post:
      operationId: searchSimilarProperties
      summary: Search similar properties by text
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                query:
                  type: string
      responses:
        '200':
          description: Vector search result
          content:
            application/json:
              schema:
                type: object

  /github/{owner}/{repo}:
    get:
      operationId: